### ISSUE TITLE
Error messaging when trying to get the app to read data generated from the `kinesis-example-scala-producer`

### ISSUE THREAD

**Issue by yalisassoon** [snowplow-archive/kinesis-example-scala-consumer#7]
Hi @bamos 

I've tried to get the application to consume data produced by the [kinesis-example-scala-producer](https://github.com/snowplow/kinesis-example-scala-producer). The producer config file is as follows:

``` json
producer {
  logging: true
  aws {
    access-key: "###"
    secret-key: "###"
  }
  stream {
    name: "snowplow_test_stream"
    size: 1
    data-type: thrift # Possible values: [string, thrift]
  }
  events {
    ordered: false
    limit: 0 # Infinite
  }
  active-polling {
    duration: 600
    interval: 20
  }
}
```

I then run the example consumer with the following config:

``` json
consumer {
  aws {
    access-key: "###"
    secret-key: "###"
  }
  stream {
    app-name: "SnowplowExampleConsumer"
    stream-name: "snowplow_test_stream"

    # LATEST: most recent data.
    # TRIM_HORIZON: oldest available data.
    # Note: This only effects the first run of this application
    # on a stream.
    initial-position = "TRIM_HORIZON"

    data-type: thrift # Possible values: [string, thrift]
    endpoint: "https://kinesis.us-east-1.amazonaws.com"
  }
}
```

I get the following really puzzling error message. I've tried changing the `data-type` from thrift to string and changing the `initial-position` from 'TRIM_HORIZON' to 'LATEST' but always get the same error:

```
SEVERE: Caught exception: 
com.amazonaws.services.kinesis.model.InvalidArgumentException: Status Code: 400, AWS Service: AmazonKinesis, AWS Request ID: c6db9d70-7d1a-11e3-b6cd-479c5f9d88f5, AWS Error Code: InvalidArgumentException, AWS Error Message: StartingSequenceNumber 49535377526404015406016317517678869977147935747381133313 used in GetShardIterator on shard shardId-000000000000 in stream snowplow_test_stream under account 889434468096 is invalid because it did not come from this stream.
```

Do you have any idea what might be causing this?

**Comment by bamos** [comment]
Hi @yalisassoon - yes, confusing message. I've seen this before. Slightly summarizing from the [documentation](http://docs.aws.amazon.com/kinesis/latest/dev/kinesis-record-processor-app.html), Amazon maintains a DynamoDB table associated with each application name, which stores information about the stream and the data the application has received or needs to receive.

Because of this, whenever the `stream-name` is changed and the `app-name` is left the same, the consumer doesn't know what to do because the DynamoDB has data to read from a nonexistent portion of the new stream.

Solution: Change `app-name` whenever `stream-name` is changed to reconstruct the DynamoDB table.

I'm updating the config in this and the enricher to read:

```
    stream-name: "snowplow_thrift"

    # `app-name` is used for a DynamoDB table to maintain stream state.
    app-name: SnowplowExampleConsumer-${consumer.stream.stream-name}
```

Let me know if there's anything else!

**Comment by alexanderdean** [comment]
Great catch guys!

**Comment by yalisassoon** [comment]
Thanks @bamos - somehow I missed your reply yesterday. Will retry it now!

**Comment by yalisassoon** [comment]
Working a treat :-)

**Comment by piggybox** [comment]
Got this weird error as well and came cross the solution here. Thanks!
